### PR TITLE
Update sync-coding.yml dev

### PR DESCRIPTION
**Pull request by Colsrch**
dev分支的对应curl命令

## PR Checklist 

- [ ] 我已提交主题文档更新PR | [Docs](https://github.com/volantis-x/community/) in [volantis website](https://volantis.js.org/)  have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [x] Build & CI related changes.
- [ ] Documentation.
- [ ] Translation.
- [ ] Other... Please describe:

## Others

- Issue resolved: 

- Screenshots with this changes: 

- Link to demo site with this changes:

### CODE REVIEW

**Comment by Colsrch** [comment]
不行 不行，不能获取到触发工作流的分支名还是得写俩yml

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/dev/.github/workflows/test-deploy.yml#L10

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo  https://volantis.js.org - volantis-x/hexo-theme-volantis</div></blockquote>

**Comment by MHuiG** [comment]
注意dev会合并到master里

**Comment by Colsrch** [comment]
@MHuiG 这样吗

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/actions/runs/551394618

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo  https://volantis.js.org - volantis-x/hexo-theme-volantis</div></blockquote>

**Pull request merged**
